<!-- START of: finna - reservationlist/bulk-action-buttons.phtml -->
<?php if (isset($list)): ?>
  <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($list['id'])?>">
  <input type="hidden" name="listName" value="<?=$this->escapeHtmlAttr($list['title'])?>">
  <input type="hidden" name="listDescription" value="<?=$this->escapeHtmlAttr($list['description'])?>">
<?php endif; ?>
<?php $user = $this->auth()->getUserObject(); ?>
<div class="bulk-action-buttons-row hidden-print">
  <?php
  $socialConfig = $this->config()->get('config')['Social'];
  $multiPageSelection = $socialConfig['multi_page_favorites_selection'] ?? true;
  $checkboxSelectAllType = $socialConfig['checkbox_select_all_favorites_type'] ?? 'both';
  ?>
  <div class="bulkActionButtons bulk-action-buttons-col">
    <div class="mylist-functions btn-group">
      <span class="sr-only"><?=$this->transEsc('bulk_noitems_advice')?></span>
      <?php if ($this->list && $user): ?>
        <button class="btn btn-primary" id="<?=$this->idPrefix?>delete_list_items_<?=null !== $this->list ? $this->escapeHtmlAttr($this->list['id']) : ''?>" type="submit" name="delete" value="<?=$this->transEscAttr('Delete')?>" title="<?=$this->transEsc('delete_selected')?>" disabled<?php if($this->formAttr):?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>><?=$this->transEsc('Delete')?></button>
      <?php endif; ?>
    </div>
  </div>
  <ul class="selection-controls-bar checkboxFilter">
    <?php if (in_array($checkboxSelectAllType, ['on_page', 'both'])): ?>
      <li class="bulk-checkbox">
        <input type="checkbox" name="selectAll" class="checkbox-select-all" id="myresearchCheckAll">
        <label for="myresearchCheckAll"><?=$this->transEsc('select_all_on_page')?></label>
      </li>
    <?php endif; ?>
    <?php if ($multiPageSelection && in_array($checkboxSelectAllType, ['global', 'both'])): ?>
      <li class="bulk-checkbox">
        <div class="select-all-global hidden">
          <input type="checkbox" name="selectAllGlobal" class="checkbox-select-all-global" id="myresearchCheckAllGlobal">
          <label for="myresearchCheckAllGlobal"><?=$this->transEsc('select_all')?></label>
        </div>
      </li>
    <?php endif; ?>
    <?php if ($multiPageSelection): ?>
      <li>
        <button type="button" class="clear-selection hidden"></button>
      </li>
    <?php endif; ?>
  </ul>
  <div class="clearfix"></div>
</div>
<!-- END of: finna - reservationlist/bulk-action-buttons.phtml -->
